<a href="https://colab.research.google.com/github/manaswiniyoshitha2006-netizen/ML-Evaluation/blob/main/notebooks/regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## *Problem Overview*

This project focuses on developing a machine learning based
telecommunications customer intelligence system.

The project uses customer demographic, tenure, service, billing,
satisfaction and behavioral information to develop predictive models.

The Regression track focuses on estimating Customer Lifetime Value (CLTV).
The Classification track focuses on customer churn prediction.

## *Problem Statement*

Telecommunications companies need to understand the value of their
customers in order to support effective customer management and
retention strategies.

The objective of the Regression track is to develop machine learning
models that estimate the Customer Lifetime Value (CLTV) of a customer
using demographic, tenure, service, billing and satisfaction-related
features.

### *Regression Objective*

The regression task treats CLTV as the continuous target variable.

The project compares multiple regression algorithms and evaluates them
using R², RMSE and MAE on a common held-out test set.

## *Import Required Libraries*

### *Import Python Libraries*

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import (
    train_test_split,
    GridSearchCV,
    KFold,
    cross_val_score
)

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import (
    OneHotEncoder,
    StandardScaler,
    PolynomialFeatures
)

from sklearn.linear_model import (
    LinearRegression,
    Ridge,
    Lasso,
    ElasticNet
)

from sklearn.metrics import (
    r2_score,
    mean_squared_error,
    mean_absolute_error
)

import warnings
warnings.filterwarnings("ignore")

sns.set_theme(style="whitegrid")

RANDOM_STATE = 42

### *Library Purpose*

Pandas and NumPy are used for data manipulation and numerical operations.

Matplotlib and Seaborn are used for exploratory data visualisation.

Scikit-learn is used for preprocessing, model training, hyperparameter
tuning and evaluation.

A random state of 42 is used wherever applicable to ensure reproducibility.

## *Dataset Loading*

### *Load Raw Dataset*

In [8]:
!git clone https://github.com/manaswiniyoshitha2006-netizen/ML-Evaluation.git
%cd ML-Evaluation

fatal: destination path 'ML-Evaluation' already exists and is not an empty directory.
/content/ML-Evaluation

In [10]:
!ls data

TelcoCustomerChurn.csv

In [11]:
df_raw = pd.read_csv("data/TelcoCustomerChurn.csv")

df = df_raw.copy()

print("Dataset loaded successfully.")

Dataset loaded successfully.

In [ ]:
df_raw = pd.read_csv("TelcoCustomerChurn.csv")

df = df_raw.copy()

print("Dataset loaded successfully.")

### *Dataset Dimensions*

In [12]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 7043
Number of columns: 50

### *First Five Records*

In [13]:
df.head()

,CustomerID,Gender,Age,Under30,SeniorCitizen,Married,Dependents,NumberofDependents,Country,State,...,TotalExtraDataCharges,TotalLongDistanceCharges,TotalRevenue,SatisfactionScore,CustomerStatus,ChurnLabel,ChurnScore,CLTV,ChurnCategory,ChurnReason
0,8779-QRDMV,Male,78,No,Yes,No,No,0,United States,California,...,20,0.00,59.65,3,Churned,Yes,91,5433,Competitor,Competitor offered more data
1,7495-OOKFY,Female,74,No,Yes,Yes,Yes,1,United States,California,...,0,390.80,1024.10,3,Churned,Yes,69,5302,Competitor,Competitor made better offer
2,1658-BYGOY,Male,71,No,Yes,No,Yes,3,United States,California,...,0,203.94,1910.88,2,Churned,Yes,81,3179,Competitor,Competitor made better offer
3,4598-XLKNJ,Female,78,No,Yes,Yes,Yes,1,United States,California,...,0,494.00,2995.07,2,Churned,Yes,88,5337,Dissatisfaction,Limited range of services
4,4846-WHAFZ,Female,80,No,Yes,Yes,Yes,1,United States,California,...,0,234.21,3102.36,2,Churned,Yes,67,2793,Price,Extra data charges

### *Last Five Records*

In [15]:
df.tail()

,CustomerID,Gender,Age,Under30,SeniorCitizen,Married,Dependents,NumberofDependents,Country,State,...,TotalExtraDataCharges,TotalLongDistanceCharges,TotalRevenue,SatisfactionScore,CustomerStatus,ChurnLabel,ChurnScore,CLTV,ChurnCategory,ChurnReason
7038,2569-WGERO,Female,30,No,No,No,No,0,United States,California,...,0,1639.44,3039.53,5,Stayed,No,45,5306,NaN,NaN
7039,6840-RESVB,Male,38,No,No,Yes,Yes,2,United States,California,...,0,865.20,2807.47,3,Stayed,No,59,2140,NaN,NaN
7040,2234-XADUH,Female,30,No,No,Yes,Yes,2,United States,California,...,0,2135.52,9453.04,4,Stayed,No,71,5560,NaN,NaN
7041,4801-JZAZL,Female,32,No,No,Yes,Yes,2,United States,California,...,0,0.00,319.21,4,Stayed,No,59,2793,NaN,NaN
7042,3186-AJIEK,Male,44,No,No,No,No,0,United States,California,...,0,2043.36,8887.86,4,Stayed,No,38,5097,NaN,NaN

### *Column Names*

In [16]:
df.columns.tolist()

['CustomerID',
 'Gender',
 'Age',
 'Under30',
 'SeniorCitizen',
 'Married',
 'Dependents',
 'NumberofDependents',
 'Country',
 'State',
 'City',
 'ZipCode',
 'Latitude',
 'Longitude',
 'Population',
 'Quarter',
 'ReferredaFriend',
 'Number_of_Referrals',
 'TenureinMonths',
 'Offer',
 'PhoneService',
 'AvgMonthlyLongDistanceCharges',
 'MultipleLines',
 'InternetService',
 'InternetType',
 'AvgMonthlyGBDownload',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtectionPlan',
 'PremiumTechSupport',
 'StreamingTV',
 'StreamingMovies',
 'StreamingMusic',
 'UnlimitedData',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharge',
 'TotalCharges',
 'TotalRefunds',
 'TotalExtraDataCharges',
 'TotalLongDistanceCharges',
 'TotalRevenue',
 'SatisfactionScore',
 'CustomerStatus',
 'ChurnLabel',
 'ChurnScore',
 'CLTV',
 'ChurnCategory',
 'ChurnReason']

## *Dataset Audit*

### *Dataset Information*

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 50 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   CustomerID                     7043 non-null   object
 1   Gender                         7043 non-null   object
 2   Age                            7043 non-null   int64
 3   Under30                        7043 non-null   object
 4   SeniorCitizen                  7043 non-null   object
 5   Married                        7043 non-null   object
 6   Dependents                     7043 non-null   object
 7   NumberofDependents             7043 non-null   int64
 8   Country                        7043 non-null   object
 9   State                          7043 non-null   object
 10  City                           7043 non-null   object
 11  ZipCode                        7043 non-null   int64
 12  Latitude                       7043 non-null   float64
 13  Longitude                      7043 non-null   float64
 14  Population                     7043 non-null   int64
 15  Quarter                        7043 non-null   object
 16  ReferredaFriend                7043 non-null   object
 17  Number_of_Referrals            7043 non-null   int64
 18  TenureinMonths                 7043 non-null   int64
 19  Offer                          3166 non-null   object
 20  PhoneService                   7043 non-null   object
 21  AvgMonthlyLongDistanceCharges  7043 non-null   float64
 22  MultipleLines                  7043 non-null   object
 23  InternetService                7043 non-null   object
 24  InternetType                   5517 non-null   object
 25  AvgMonthlyGBDownload           7043 non-null   int64
 26  OnlineSecurity                 7043 non-null   object
 27  OnlineBackup                   7043 non-null   object
 28  DeviceProtectionPlan           7043 non-null   object
 29  PremiumTechSupport             7043 non-null   object
 30  StreamingTV                    7043 non-null   object
 31  StreamingMovies                7043 non-null   object
 32  StreamingMusic                 7043 non-null   object
 33  UnlimitedData                  7043 non-null   object
 34  Contract                       7043 non-null   object
 35  PaperlessBilling               7043 non-null   object
 36  PaymentMethod                  7043 non-null   object
 37  MonthlyCharge                  7043 non-null   float64
 38  TotalCharges                   7043 non-null   float64
 39  TotalRefunds                   7043 non-null   float64
 40  TotalExtraDataCharges          7043 non-null   int64
 41  TotalLongDistanceCharges       7043 non-null   float64
 42  TotalRevenue                   7043 non-null   float64
 43  SatisfactionScore              7043 non-null   int64
 44  CustomerStatus                 7043 non-null   object
 45  ChurnLabel                     7043 non-null   object
 46  ChurnScore                     7043 non-null   int64
 47  CLTV                           7043 non-null   int64
 48  ChurnCategory                  1869 non-null   object
 49  ChurnReason                    1869 non-null   object
dtypes: float64(8), int64(11), object(31)
memory usage: 2.7+ MB

### *Data Types*

In [18]:
df.dtypes

CustomerID                        object
Gender                            object
Age                                int64
Under30                           object
SeniorCitizen                     object
Married                           object
Dependents                        object
NumberofDependents                 int64
Country                           object
State                             object
City                              object
ZipCode                            int64
Latitude                         float64
Longitude                        float64
Population                         int64
Quarter                           object
ReferredaFriend                   object
Number_of_Referrals                int64
TenureinMonths                     int64
Offer                             object
PhoneService                      object
AvgMonthlyLongDistanceCharges    float64
MultipleLines                     object
InternetService                   object
InternetType                      object
AvgMonthlyGBDownload               int64
OnlineSecurity                    object
OnlineBackup                      object
DeviceProtectionPlan              object
PremiumTechSupport                object
StreamingTV                       object
StreamingMovies                   object
StreamingMusic                    object
UnlimitedData                     object
Contract                          object
PaperlessBilling                  object
PaymentMethod                     object
MonthlyCharge                    float64
TotalCharges                     float64
TotalRefunds                     float64
TotalExtraDataCharges              int64
TotalLongDistanceCharges         float64
TotalRevenue                     float64
SatisfactionScore                  int64
CustomerStatus                    object
ChurnLabel                        object
ChurnScore                         int64
CLTV                               int64
ChurnCategory                     object
ChurnReason                       object
dtype: object

### *Numerical Descriptive Statistics*

In [19]:
df.describe()

,Age,NumberofDependents,ZipCode,Latitude,Longitude,Population,Number_of_Referrals,TenureinMonths,AvgMonthlyLongDistanceCharges,AvgMonthlyGBDownload,MonthlyCharge,TotalCharges,TotalRefunds,TotalExtraDataCharges,TotalLongDistanceCharges,TotalRevenue,SatisfactionScore,ChurnScore,CLTV
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,46.509726,0.468692,93486.070567,36.197455,-119.756684,22139.603294,1.951867,32.386767,22.958954,20.515405,64.761692,2280.381264,1.962182,6.860713,749.099262,3034.379056,3.244924,58.505040,4400.295755
std,16.750352,0.962802,1856.767505,2.468929,2.154425,21152.392837,3.001199,24.542061,15.448113,20.418940,30.090047,2266.220462,7.902614,25.104978,846.660055,2865.204542,1.201657,21.170031,1183.057152
min,19.000000,0.000000,90001.000000,32.555828,-124.301372,11.000000,0.000000,1.000000,0.000000,0.000000,18.250000,18.800000,0.000000,0.000000,0.000000,21.360000,1.000000,5.000000,2003.000000
25%,32.000000,0.000000,92101.000000,33.990646,-121.788090,2344.000000,0.000000,9.000000,9.210000,3.000000,35.500000,400.150000,0.000000,0.000000,70.545000,605.610000,3.000000,40.000000,3469.000000
50%,46.000000,0.000000,93518.000000,36.205465,-119.595293,17554.000000,0.000000,29.000000,22.890000,17.000000,70.350000,1394.550000,0.000000,0.000000,401.440000,2108.640000,3.000000,61.000000,4527.000000
75%,60.000000,0.000000,95329.000000,38.161321,-117.969795,36125.000000,3.000000,55.000000,36.395000,27.000000,89.850000,3786.600000,0.000000,0.000000,1191.100000,4801.145000,4.000000,75.500000,5380.500000
max,80.000000,9.000000,96150.000000,41.962127,-114.192901,105285.000000,11.000000,72.000000,49.990000,85.000000,118.750000,8684.800000,49.790000,150.000000,3564.720000,11979.340000,5.000000,96.000000,6500.000000

### *Categorical Descriptive Statistics*

In [20]:
df.describe(include="object")

,CustomerID,Gender,Under30,SeniorCitizen,Married,Dependents,Country,State,City,Quarter,...,StreamingMovies,StreamingMusic,UnlimitedData,Contract,PaperlessBilling,PaymentMethod,CustomerStatus,ChurnLabel,ChurnCategory,ChurnReason
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,...,7043,7043,7043,7043,7043,7043,7043,7043,1869,1869
unique,7043,2,2,2,2,2,1,1,1106,1,...,2,2,2,3,2,3,3,2,5,20
top,3186-AJIEK,Male,No,No,No,No,United States,California,Los Angeles,Q3,...,No,No,Yes,Month-to-Month,Yes,Bank Withdrawal,Stayed,No,Competitor,Competitor had better devices
freq,1,3555,5642,5901,3641,5416,7043,7043,293,7043,...,4311,4555,4745,3610,4171,3909,4720,5174,841,313

### *Numerical and Categorical Feature Identification*

In [21]:
numeric_columns = df.select_dtypes(
    include=np.number
).columns.tolist()

categorical_columns = df.select_dtypes(
    include="object"
).columns.tolist()

print("Numerical features:")
print(numeric_columns)

print("\nCategorical features:")
print(categorical_columns)

Numerical features:
['Age', 'NumberofDependents', 'ZipCode', 'Latitude', 'Longitude', 'Population', 'Number_of_Referrals', 'TenureinMonths', 'AvgMonthlyLongDistanceCharges', 'AvgMonthlyGBDownload', 'MonthlyCharge', 'TotalCharges', 'TotalRefunds', 'TotalExtraDataCharges', 'TotalLongDistanceCharges', 'TotalRevenue', 'SatisfactionScore', 'ChurnScore', 'CLTV']

Categorical features:
['CustomerID', 'Gender', 'Under30', 'SeniorCitizen', 'Married', 'Dependents', 'Country', 'State', 'City', 'Quarter', 'ReferredaFriend', 'Offer', 'PhoneService', 'MultipleLines', 'InternetService', 'InternetType', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtectionPlan', 'PremiumTechSupport', 'StreamingTV', 'StreamingMovies', 'StreamingMusic', 'UnlimitedData', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'CustomerStatus', 'ChurnLabel', 'ChurnCategory', 'ChurnReason']